services:
  mongo:
    image: mongo:latest
    container_name: stocky-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: stockydb
    networks:
      - stocky-network

  stocky-api:
    build: ./stocky-api
    container_name: stocky-api
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/stockydb
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./stocky-api:/app
      - /app/node_modules
    restart: always
    networks:
      - stocky-network

networks:
  stocky-network:
    driver: bridge
